[package]
name = "dns-update-digital-ocean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digitalocean = "0.1.1"
reqwest = "0.9.11"
log = "0.4.20"
